// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/marcos-wz/capstone/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// ReaderRepo is an autogenerated mock type for the ReaderRepo type
type ReaderRepo struct {
	mock.Mock
}

// ReadFruits provides a mock function with given fields:
func (_m *ReaderRepo) ReadFruits() ([]entity.Fruit, *entity.ReadFruitsError) {
	ret := _m.Called()

	var r0 []entity.Fruit
	if rf, ok := ret.Get(0).(func() []entity.Fruit); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Fruit)
		}
	}

	var r1 *entity.ReadFruitsError
	if rf, ok := ret.Get(1).(func() *entity.ReadFruitsError); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entity.ReadFruitsError)
		}
	}

	return r0, r1
}
