// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: filtercc.proto

package filterccpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterCCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FilterCCRequest) Reset() {
	*x = FilterCCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filtercc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterCCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterCCRequest) ProtoMessage() {}

func (x *FilterCCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filtercc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterCCRequest.ProtoReflect.Descriptor instead.
func (*FilterCCRequest) Descriptor() ([]byte, []int) {
	return file_filtercc_proto_rawDescGZIP(), []int{0}
}

type FilterCCResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FilterCCResponse) Reset() {
	*x = FilterCCResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filtercc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterCCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterCCResponse) ProtoMessage() {}

func (x *FilterCCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filtercc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterCCResponse.ProtoReflect.Descriptor instead.
func (*FilterCCResponse) Descriptor() ([]byte, []int) {
	return file_filtercc_proto_rawDescGZIP(), []int{1}
}

var File_filtercc_proto protoreflect.FileDescriptor

var file_filtercc_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x63, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x63, 0x61, 0x70, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x43, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a,
	0x10, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x43, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x61, 0x72, 0x63, 0x6f, 0x73, 0x2d, 0x77, 0x7a, 0x2f, 0x63, 0x61, 0x70, 0x73, 0x74, 0x6f,
	0x6e, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x63,
	0x63, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_filtercc_proto_rawDescOnce sync.Once
	file_filtercc_proto_rawDescData = file_filtercc_proto_rawDesc
)

func file_filtercc_proto_rawDescGZIP() []byte {
	file_filtercc_proto_rawDescOnce.Do(func() {
		file_filtercc_proto_rawDescData = protoimpl.X.CompressGZIP(file_filtercc_proto_rawDescData)
	})
	return file_filtercc_proto_rawDescData
}

var file_filtercc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_filtercc_proto_goTypes = []interface{}{
	(*FilterCCRequest)(nil),  // 0: capstone.FilterCCRequest
	(*FilterCCResponse)(nil), // 1: capstone.FilterCCResponse
}
var file_filtercc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_filtercc_proto_init() }
func file_filtercc_proto_init() {
	if File_filtercc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_filtercc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterCCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filtercc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterCCResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_filtercc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_filtercc_proto_goTypes,
		DependencyIndexes: file_filtercc_proto_depIdxs,
		MessageInfos:      file_filtercc_proto_msgTypes,
	}.Build()
	File_filtercc_proto = out.File
	file_filtercc_proto_rawDesc = nil
	file_filtercc_proto_goTypes = nil
	file_filtercc_proto_depIdxs = nil
}
