// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: internal/fruitpb/fruit.proto

package fruitpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeightUnit int32

const (
	WeightUnit_KG WeightUnit = 0
	WeightUnit_LB WeightUnit = 1
)

// Enum value maps for WeightUnit.
var (
	WeightUnit_name = map[int32]string{
		0: "KG",
		1: "LB",
	}
	WeightUnit_value = map[string]int32{
		"KG": 0,
		"LB": 1,
	}
)

func (x WeightUnit) Enum() *WeightUnit {
	p := new(WeightUnit)
	*p = x
	return p
}

func (x WeightUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WeightUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_fruitpb_fruit_proto_enumTypes[0].Descriptor()
}

func (WeightUnit) Type() protoreflect.EnumType {
	return &file_internal_fruitpb_fruit_proto_enumTypes[0]
}

func (x WeightUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WeightUnit.Descriptor instead.
func (WeightUnit) EnumDescriptor() ([]byte, []int) {
	return file_internal_fruitpb_fruit_proto_rawDescGZIP(), []int{0}
}

type FiltersAllowed int32

const (
	FiltersAllowed_ID      FiltersAllowed = 0
	FiltersAllowed_NAME    FiltersAllowed = 1
	FiltersAllowed_COLOR   FiltersAllowed = 2
	FiltersAllowed_COUNTRY FiltersAllowed = 3
)

// Enum value maps for FiltersAllowed.
var (
	FiltersAllowed_name = map[int32]string{
		0: "ID",
		1: "NAME",
		2: "COLOR",
		3: "COUNTRY",
	}
	FiltersAllowed_value = map[string]int32{
		"ID":      0,
		"NAME":    1,
		"COLOR":   2,
		"COUNTRY": 3,
	}
)

func (x FiltersAllowed) Enum() *FiltersAllowed {
	p := new(FiltersAllowed)
	*p = x
	return p
}

func (x FiltersAllowed) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FiltersAllowed) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_fruitpb_fruit_proto_enumTypes[1].Descriptor()
}

func (FiltersAllowed) Type() protoreflect.EnumType {
	return &file_internal_fruitpb_fruit_proto_enumTypes[1]
}

func (x FiltersAllowed) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FiltersAllowed.Descriptor instead.
func (FiltersAllowed) EnumDescriptor() ([]byte, []int) {
	return file_internal_fruitpb_fruit_proto_rawDescGZIP(), []int{1}
}

type Fruit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description  string     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Color        string     `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Unit         WeightUnit `protobuf:"varint,5,opt,name=unit,proto3,enum=fruit.WeightUnit" json:"unit,omitempty"`
	Price        float32    `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	Stock        uint32     `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	CaducateDays uint32     `protobuf:"varint,8,opt,name=caducate_days,json=caducateDays,proto3" json:"caducate_days,omitempty"`
	Country      string     `protobuf:"bytes,9,opt,name=country,proto3" json:"country,omitempty"`
	CreatedAt    string     `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    string     `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Fruit) Reset() {
	*x = Fruit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_fruitpb_fruit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fruit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fruit) ProtoMessage() {}

func (x *Fruit) ProtoReflect() protoreflect.Message {
	mi := &file_internal_fruitpb_fruit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fruit.ProtoReflect.Descriptor instead.
func (*Fruit) Descriptor() ([]byte, []int) {
	return file_internal_fruitpb_fruit_proto_rawDescGZIP(), []int{0}
}

func (x *Fruit) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Fruit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Fruit) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Fruit) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Fruit) GetUnit() WeightUnit {
	if x != nil {
		return x.Unit
	}
	return WeightUnit_KG
}

func (x *Fruit) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Fruit) GetStock() uint32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Fruit) GetCaducateDays() uint32 {
	if x != nil {
		return x.CaducateDays
	}
	return 0
}

func (x *Fruit) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Fruit) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Fruit) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type FilterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter FiltersAllowed `protobuf:"varint,1,opt,name=filter,proto3,enum=fruit.FiltersAllowed" json:"filter,omitempty"`
	Value  string         `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *FilterRequest) Reset() {
	*x = FilterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_fruitpb_fruit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRequest) ProtoMessage() {}

func (x *FilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_fruitpb_fruit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRequest.ProtoReflect.Descriptor instead.
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return file_internal_fruitpb_fruit_proto_rawDescGZIP(), []int{1}
}

func (x *FilterRequest) GetFilter() FiltersAllowed {
	if x != nil {
		return x.Filter
	}
	return FiltersAllowed_ID
}

func (x *FilterRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type FilterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code                int32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Error               string                `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Fruits              []*Fruit              `protobuf:"bytes,3,rep,name=fruits,proto3" json:"fruits,omitempty"`
	ReadRecordCsvErrors []*ReadRecordCSVError `protobuf:"bytes,4,rep,name=read_record_csv_errors,json=readRecordCsvErrors,proto3" json:"read_record_csv_errors,omitempty"` // Fruit fruit = 1;
}

func (x *FilterResponse) Reset() {
	*x = FilterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_fruitpb_fruit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterResponse) ProtoMessage() {}

func (x *FilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_fruitpb_fruit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterResponse.ProtoReflect.Descriptor instead.
func (*FilterResponse) Descriptor() ([]byte, []int) {
	return file_internal_fruitpb_fruit_proto_rawDescGZIP(), []int{2}
}

func (x *FilterResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FilterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FilterResponse) GetFruits() []*Fruit {
	if x != nil {
		return x.Fruits
	}
	return nil
}

func (x *FilterResponse) GetReadRecordCsvErrors() []*ReadRecordCSVError {
	if x != nil {
		return x.ReadRecordCsvErrors
	}
	return nil
}

type ParseFieldCSVError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field      string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Value      string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Validation string `protobuf:"bytes,3,opt,name=validation,proto3" json:"validation,omitempty"`
	Error      string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ParseFieldCSVError) Reset() {
	*x = ParseFieldCSVError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_fruitpb_fruit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseFieldCSVError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseFieldCSVError) ProtoMessage() {}

func (x *ParseFieldCSVError) ProtoReflect() protoreflect.Message {
	mi := &file_internal_fruitpb_fruit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseFieldCSVError.ProtoReflect.Descriptor instead.
func (*ParseFieldCSVError) Descriptor() ([]byte, []int) {
	return file_internal_fruitpb_fruit_proto_rawDescGZIP(), []int{3}
}

func (x *ParseFieldCSVError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ParseFieldCSVError) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ParseFieldCSVError) GetValidation() string {
	if x != nil {
		return x.Validation
	}
	return ""
}

func (x *ParseFieldCSVError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ParseRecordCSVError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record uint32                `protobuf:"varint,1,opt,name=record,proto3" json:"record,omitempty"`
	Errors []*ParseFieldCSVError `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *ParseRecordCSVError) Reset() {
	*x = ParseRecordCSVError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_fruitpb_fruit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseRecordCSVError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRecordCSVError) ProtoMessage() {}

func (x *ParseRecordCSVError) ProtoReflect() protoreflect.Message {
	mi := &file_internal_fruitpb_fruit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRecordCSVError.ProtoReflect.Descriptor instead.
func (*ParseRecordCSVError) Descriptor() ([]byte, []int) {
	return file_internal_fruitpb_fruit_proto_rawDescGZIP(), []int{4}
}

func (x *ParseRecordCSVError) GetRecord() uint32 {
	if x != nil {
		return x.Record
	}
	return 0
}

func (x *ParseRecordCSVError) GetErrors() []*ParseFieldCSVError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ReadRecordCSVError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Error        string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ParserErrors []*ParseRecordCSVError `protobuf:"bytes,3,rep,name=parser_errors,json=parserErrors,proto3" json:"parser_errors,omitempty"`
}

func (x *ReadRecordCSVError) Reset() {
	*x = ReadRecordCSVError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_fruitpb_fruit_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadRecordCSVError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRecordCSVError) ProtoMessage() {}

func (x *ReadRecordCSVError) ProtoReflect() protoreflect.Message {
	mi := &file_internal_fruitpb_fruit_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRecordCSVError.ProtoReflect.Descriptor instead.
func (*ReadRecordCSVError) Descriptor() ([]byte, []int) {
	return file_internal_fruitpb_fruit_proto_rawDescGZIP(), []int{5}
}

func (x *ReadRecordCSVError) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ReadRecordCSVError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReadRecordCSVError) GetParserErrors() []*ParseRecordCSVError {
	if x != nil {
		return x.ParserErrors
	}
	return nil
}

// LOADER ---------------------------------------------
type LoaderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoaderRequest) Reset() {
	*x = LoaderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_fruitpb_fruit_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoaderRequest) ProtoMessage() {}

func (x *LoaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_fruitpb_fruit_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoaderRequest.ProtoReflect.Descriptor instead.
func (*LoaderRequest) Descriptor() ([]byte, []int) {
	return file_internal_fruitpb_fruit_proto_rawDescGZIP(), []int{6}
}

type LoaderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoaderResponse) Reset() {
	*x = LoaderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_fruitpb_fruit_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoaderResponse) ProtoMessage() {}

func (x *LoaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_fruitpb_fruit_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoaderResponse.ProtoReflect.Descriptor instead.
func (*LoaderResponse) Descriptor() ([]byte, []int) {
	return file_internal_fruitpb_fruit_proto_rawDescGZIP(), []int{7}
}

// Filter Concurrency --------------------
type FilterCCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FilterCCRequest) Reset() {
	*x = FilterCCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_fruitpb_fruit_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterCCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterCCRequest) ProtoMessage() {}

func (x *FilterCCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_fruitpb_fruit_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterCCRequest.ProtoReflect.Descriptor instead.
func (*FilterCCRequest) Descriptor() ([]byte, []int) {
	return file_internal_fruitpb_fruit_proto_rawDescGZIP(), []int{8}
}

type FilterCCResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FilterCCResponse) Reset() {
	*x = FilterCCResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_fruitpb_fruit_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterCCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterCCResponse) ProtoMessage() {}

func (x *FilterCCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_fruitpb_fruit_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterCCResponse.ProtoReflect.Descriptor instead.
func (*FilterCCResponse) Descriptor() ([]byte, []int) {
	return file_internal_fruitpb_fruit_proto_rawDescGZIP(), []int{9}
}

var File_internal_fruitpb_fruit_proto protoreflect.FileDescriptor

var file_internal_fruitpb_fruit_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x66, 0x72, 0x75, 0x69, 0x74,
	0x70, 0x62, 0x2f, 0x66, 0x72, 0x75, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x66, 0x72, 0x75, 0x69, 0x74, 0x22, 0xb3, 0x02, 0x0a, 0x05, 0x46, 0x72, 0x75, 0x69, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x25, 0x0a, 0x04, 0x75,
	0x6e, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x66, 0x72, 0x75, 0x69,
	0x74, 0x2e, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x04, 0x75, 0x6e,
	0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x23,
	0x0a, 0x0d, 0x63, 0x61, 0x64, 0x75, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x61, 0x64, 0x75, 0x63, 0x61, 0x74, 0x65, 0x44,
	0x61, 0x79, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x54, 0x0a, 0x0d, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x06,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x66,
	0x72, 0x75, 0x69, 0x74, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x41, 0x6c, 0x6c, 0x6f,
	0x77, 0x65, 0x64, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0xb0, 0x01, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x24,
	0x0a, 0x06, 0x66, 0x72, 0x75, 0x69, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x66, 0x72, 0x75, 0x69, 0x74, 0x2e, 0x46, 0x72, 0x75, 0x69, 0x74, 0x52, 0x06, 0x66, 0x72,
	0x75, 0x69, 0x74, 0x73, 0x12, 0x4e, 0x0a, 0x16, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x5f, 0x63, 0x73, 0x76, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x66, 0x72, 0x75, 0x69, 0x74, 0x2e, 0x52, 0x65, 0x61,
	0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x53, 0x56, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x13, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x73, 0x76, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x22, 0x76, 0x0a, 0x12, 0x50, 0x61, 0x72, 0x73, 0x65, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x43, 0x53, 0x56, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x60, 0x0a, 0x13,
	0x50, 0x61, 0x72, 0x73, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x53, 0x56, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x31, 0x0a, 0x06, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x66, 0x72,
	0x75, 0x69, 0x74, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x43, 0x53,
	0x56, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x7f,
	0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x53, 0x56, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x3f,
	0x0a, 0x0d, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x66, 0x72, 0x75, 0x69, 0x74, 0x2e, 0x50, 0x61,
	0x72, 0x73, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x53, 0x56, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x0c, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22,
	0x0f, 0x0a, 0x0d, 0x4c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x43, 0x43, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x43,
	0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x1c, 0x0a, 0x0a, 0x77, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x06, 0x0a, 0x02, 0x4b, 0x47, 0x10, 0x00, 0x12,
	0x06, 0x0a, 0x02, 0x4c, 0x42, 0x10, 0x01, 0x2a, 0x3a, 0x0a, 0x0e, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x44, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x43,
	0x4f, 0x4c, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x52,
	0x59, 0x10, 0x03, 0x32, 0x47, 0x0a, 0x0c, 0x46, 0x72, 0x75, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x2e,
	0x66, 0x72, 0x75, 0x69, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x66, 0x72, 0x75, 0x69, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x66, 0x72, 0x75, 0x69, 0x74, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_fruitpb_fruit_proto_rawDescOnce sync.Once
	file_internal_fruitpb_fruit_proto_rawDescData = file_internal_fruitpb_fruit_proto_rawDesc
)

func file_internal_fruitpb_fruit_proto_rawDescGZIP() []byte {
	file_internal_fruitpb_fruit_proto_rawDescOnce.Do(func() {
		file_internal_fruitpb_fruit_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_fruitpb_fruit_proto_rawDescData)
	})
	return file_internal_fruitpb_fruit_proto_rawDescData
}

var file_internal_fruitpb_fruit_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_fruitpb_fruit_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_fruitpb_fruit_proto_goTypes = []interface{}{
	(WeightUnit)(0),             // 0: fruit.weightUnit
	(FiltersAllowed)(0),         // 1: fruit.filtersAllowed
	(*Fruit)(nil),               // 2: fruit.Fruit
	(*FilterRequest)(nil),       // 3: fruit.FilterRequest
	(*FilterResponse)(nil),      // 4: fruit.FilterResponse
	(*ParseFieldCSVError)(nil),  // 5: fruit.ParseFieldCSVError
	(*ParseRecordCSVError)(nil), // 6: fruit.ParseRecordCSVError
	(*ReadRecordCSVError)(nil),  // 7: fruit.ReadRecordCSVError
	(*LoaderRequest)(nil),       // 8: fruit.LoaderRequest
	(*LoaderResponse)(nil),      // 9: fruit.LoaderResponse
	(*FilterCCRequest)(nil),     // 10: fruit.FilterCCRequest
	(*FilterCCResponse)(nil),    // 11: fruit.FilterCCResponse
}
var file_internal_fruitpb_fruit_proto_depIdxs = []int32{
	0, // 0: fruit.Fruit.unit:type_name -> fruit.weightUnit
	1, // 1: fruit.FilterRequest.filter:type_name -> fruit.filtersAllowed
	2, // 2: fruit.FilterResponse.fruits:type_name -> fruit.Fruit
	7, // 3: fruit.FilterResponse.read_record_csv_errors:type_name -> fruit.ReadRecordCSVError
	5, // 4: fruit.ParseRecordCSVError.errors:type_name -> fruit.ParseFieldCSVError
	6, // 5: fruit.ReadRecordCSVError.parser_errors:type_name -> fruit.ParseRecordCSVError
	3, // 6: fruit.FruitService.Filter:input_type -> fruit.FilterRequest
	4, // 7: fruit.FruitService.Filter:output_type -> fruit.FilterResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_fruitpb_fruit_proto_init() }
func file_internal_fruitpb_fruit_proto_init() {
	if File_internal_fruitpb_fruit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_fruitpb_fruit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fruit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_fruitpb_fruit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_fruitpb_fruit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_fruitpb_fruit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParseFieldCSVError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_fruitpb_fruit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParseRecordCSVError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_fruitpb_fruit_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadRecordCSVError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_fruitpb_fruit_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoaderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_fruitpb_fruit_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoaderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_fruitpb_fruit_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterCCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_fruitpb_fruit_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterCCResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_fruitpb_fruit_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_fruitpb_fruit_proto_goTypes,
		DependencyIndexes: file_internal_fruitpb_fruit_proto_depIdxs,
		EnumInfos:         file_internal_fruitpb_fruit_proto_enumTypes,
		MessageInfos:      file_internal_fruitpb_fruit_proto_msgTypes,
	}.Build()
	File_internal_fruitpb_fruit_proto = out.File
	file_internal_fruitpb_fruit_proto_rawDesc = nil
	file_internal_fruitpb_fruit_proto_goTypes = nil
	file_internal_fruitpb_fruit_proto_depIdxs = nil
}
