// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package fruitpb

import (
	context "context"
	filterccpb "github.com/marcos-wz/capstone/proto/filterccpb"
	filterpb "github.com/marcos-wz/capstone/proto/filterpb"
	loaderpb "github.com/marcos-wz/capstone/proto/loaderpb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FruitServiceClient is the client API for FruitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FruitServiceClient interface {
	Filter(ctx context.Context, in *filterpb.FilterRequest, opts ...grpc.CallOption) (FruitService_FilterClient, error)
	Loader(ctx context.Context, in *loaderpb.LoaderRequest, opts ...grpc.CallOption) (*loaderpb.LoaderResponse, error)
	FilterCC(ctx context.Context, in *filterccpb.FilterCCRequest, opts ...grpc.CallOption) (FruitService_FilterCCClient, error)
}

type fruitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFruitServiceClient(cc grpc.ClientConnInterface) FruitServiceClient {
	return &fruitServiceClient{cc}
}

func (c *fruitServiceClient) Filter(ctx context.Context, in *filterpb.FilterRequest, opts ...grpc.CallOption) (FruitService_FilterClient, error) {
	stream, err := c.cc.NewStream(ctx, &FruitService_ServiceDesc.Streams[0], "/capstone.FruitService/Filter", opts...)
	if err != nil {
		return nil, err
	}
	x := &fruitServiceFilterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FruitService_FilterClient interface {
	Recv() (*filterpb.FilterResponse, error)
	grpc.ClientStream
}

type fruitServiceFilterClient struct {
	grpc.ClientStream
}

func (x *fruitServiceFilterClient) Recv() (*filterpb.FilterResponse, error) {
	m := new(filterpb.FilterResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fruitServiceClient) Loader(ctx context.Context, in *loaderpb.LoaderRequest, opts ...grpc.CallOption) (*loaderpb.LoaderResponse, error) {
	out := new(loaderpb.LoaderResponse)
	err := c.cc.Invoke(ctx, "/capstone.FruitService/Loader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fruitServiceClient) FilterCC(ctx context.Context, in *filterccpb.FilterCCRequest, opts ...grpc.CallOption) (FruitService_FilterCCClient, error) {
	stream, err := c.cc.NewStream(ctx, &FruitService_ServiceDesc.Streams[1], "/capstone.FruitService/FilterCC", opts...)
	if err != nil {
		return nil, err
	}
	x := &fruitServiceFilterCCClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FruitService_FilterCCClient interface {
	Recv() (*filterccpb.FilterCCResponse, error)
	grpc.ClientStream
}

type fruitServiceFilterCCClient struct {
	grpc.ClientStream
}

func (x *fruitServiceFilterCCClient) Recv() (*filterccpb.FilterCCResponse, error) {
	m := new(filterccpb.FilterCCResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FruitServiceServer is the server API for FruitService service.
// All implementations must embed UnimplementedFruitServiceServer
// for forward compatibility
type FruitServiceServer interface {
	Filter(*filterpb.FilterRequest, FruitService_FilterServer) error
	Loader(context.Context, *loaderpb.LoaderRequest) (*loaderpb.LoaderResponse, error)
	FilterCC(*filterccpb.FilterCCRequest, FruitService_FilterCCServer) error
	mustEmbedUnimplementedFruitServiceServer()
}

// UnimplementedFruitServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFruitServiceServer struct {
}

func (UnimplementedFruitServiceServer) Filter(*filterpb.FilterRequest, FruitService_FilterServer) error {
	return status.Errorf(codes.Unimplemented, "method Filter not implemented")
}
func (UnimplementedFruitServiceServer) Loader(context.Context, *loaderpb.LoaderRequest) (*loaderpb.LoaderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Loader not implemented")
}
func (UnimplementedFruitServiceServer) FilterCC(*filterccpb.FilterCCRequest, FruitService_FilterCCServer) error {
	return status.Errorf(codes.Unimplemented, "method FilterCC not implemented")
}
func (UnimplementedFruitServiceServer) mustEmbedUnimplementedFruitServiceServer() {}

// UnsafeFruitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FruitServiceServer will
// result in compilation errors.
type UnsafeFruitServiceServer interface {
	mustEmbedUnimplementedFruitServiceServer()
}

func RegisterFruitServiceServer(s grpc.ServiceRegistrar, srv FruitServiceServer) {
	s.RegisterService(&FruitService_ServiceDesc, srv)
}

func _FruitService_Filter_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(filterpb.FilterRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FruitServiceServer).Filter(m, &fruitServiceFilterServer{stream})
}

type FruitService_FilterServer interface {
	Send(*filterpb.FilterResponse) error
	grpc.ServerStream
}

type fruitServiceFilterServer struct {
	grpc.ServerStream
}

func (x *fruitServiceFilterServer) Send(m *filterpb.FilterResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _FruitService_Loader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(loaderpb.LoaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FruitServiceServer).Loader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/capstone.FruitService/Loader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FruitServiceServer).Loader(ctx, req.(*loaderpb.LoaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FruitService_FilterCC_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(filterccpb.FilterCCRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FruitServiceServer).FilterCC(m, &fruitServiceFilterCCServer{stream})
}

type FruitService_FilterCCServer interface {
	Send(*filterccpb.FilterCCResponse) error
	grpc.ServerStream
}

type fruitServiceFilterCCServer struct {
	grpc.ServerStream
}

func (x *fruitServiceFilterCCServer) Send(m *filterccpb.FilterCCResponse) error {
	return x.ServerStream.SendMsg(m)
}

// FruitService_ServiceDesc is the grpc.ServiceDesc for FruitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FruitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "capstone.FruitService",
	HandlerType: (*FruitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Loader",
			Handler:    _FruitService_Loader_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Filter",
			Handler:       _FruitService_Filter_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FilterCC",
			Handler:       _FruitService_FilterCC_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fruit.proto",
}
