# default server configuration
server:
  port: 50051

data:
  csv: "data/fruits.csv"
  # "data/test/csv/fruits-test-error.csv"
  json: "data/fruits.json"

external-api:
  url: "localhost:50051/v1/fruits"

debug:
  all: false
  server: false
  rpc: false
  service: false
  repository: false