// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/marcos-wz/capstone/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// FilterService is an autogenerated mock type for the FilterService type
type FilterService struct {
	mock.Mock
}

// GetFilteredFruits provides a mock function with given fields: filter
func (_m *FilterService) GetFilteredFruits(filter *entity.FruitsFilterParams) ([]entity.Fruit, *entity.FruitFilterError) {
	ret := _m.Called(filter)

	var r0 []entity.Fruit
	if rf, ok := ret.Get(0).(func(*entity.FruitsFilterParams) []entity.Fruit); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Fruit)
		}
	}

	var r1 *entity.FruitFilterError
	if rf, ok := ret.Get(1).(func(*entity.FruitsFilterParams) *entity.FruitFilterError); ok {
		r1 = rf(filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entity.FruitFilterError)
		}
	}

	return r0, r1
}
